name: CI Pipeline

# 触发时机，这里是每次 push 代码时触发
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 拉取仓库代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Python 版本
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 安装依赖（确保有 requirements.txt 文件）
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # 运行测试
      - name: Run tests
        run: |
          pytest
